# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Luca Martorana"
resume_title:                   "Cloud Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           ""

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Italy"

resume_header_contact_info:     "Empowering cloud solutions with passion for technology and continuous learning."
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a passionate Cloud Engineer from Italy, with a strong background in IT and continuous learning. I completed my studies at the Alessandro Volta Industrial Institute in Palermo, specializing in technology and computer systems. Experienced in both software and hardware repairs, I am a tech enthusiast who constantly seeks new knowledge in the IT world. I actively follow the latest technology trends and deepen my understanding of programming languages beyond academic studies.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            ""
  resume_twitter_url:           ""
  resume_dribbble_url:          ""
  resume_facebook_url:          ""
  resume_linkedin_url:          ""
  resume_instagram_url:         ""
  resume_website_url:           ""
  resume_medium_url:            ""
resume_print_social_links:      false

# Design settings
resume_theme:                   default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts